import ProductForm from '@/components/ProductForm'
import ProductList from '@/components/ProductList'
import { signIn, signOut, useSession } from 'next-auth/react'
import Head from 'next/head'

export default function Home() {
  const { data: session } = useSession()

  return (
    <>
      <Head>
        <title>Orders</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='font-poppins relative'>
        <ProductForm />
        <ProductList />
      </main>
    </>
  )
}
